language: java

sudo: required

services:
- docker

install: true

script:
- docker build -t cabaletta/baritone .
- docker run cabaletta/baritone /bin/sh -c "./gradlew test"
- docker run cabaletta/baritone /bin/sh -c "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 128x128x24 -ac +extension GLX +render; DISPLAY=:99 BARITONE_AUTO_TEST=true ./gradlew runClient"