language: java

install: true

script:
- ./gradlew check
- export DISPLAY=:99
- export LIBGL_ALWAYS_SOFTWARE=1
- sudo apt-get update -qq --force-yes
- sudo apt-get install -qq --force-yes mesa-utils libgl1-mesa-glx libgl1-mesa-glx-dev xvfb
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
- glxinfo
- ./gradlew run