language: java

sudo: required

services:
- docker

install: true

script:
- docker build -t cabaletta/baritone .
- docker run cabaletta/baritone "./gradlew test"
- docker run cabaletta/baritone /bin/sh -c "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render; DISPLAY=:99 ./gradlew run"